---
fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git@github.com:puppetlabs/provision.git'
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 5.0.0
    cron_core:
      repo: puppetlabs-cron_core
      ref: 1.0.1
    cron:
      repo: puppet-cron
      ref: 1.3.1
