---
dist: bionic
language: ruby
services:
  - docker
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install
  - bundle exec rake -T
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - test
matrix:
  fast_finish: true
  include:
    -
      services: docker
      sudo: required
      stage: test
      script:
        - make test_puppet6
branches:
  only:
    - master
    - /^v\d/
    - litmus
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
