---
dist: bionic
language: ruby
services:
  - docker
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install
  - bundle exec rake -T
bundler_args: --without system_tests
rvm:
  - 2.5.3
matrix:
  fast_finish: true
  include:
    -
      services: docker
      sudo: required
      script:
        - bundle exec rake 'litmus:provision_list[travis_el]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
        - bundle exec rake litmus:acceptance:parallel
branches:
  only:
    - master
    - /^v\d/
    - litmus
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
